version: '3.9'

include:
  - docker-compose-backend.yaml
services:
  frontend:
    build:
      context: .
      dockerfile: my-frontend/Dockerfile.dev
    working_dir: /app
    networks:
      - my-network
    depends_on:
      - backend
    restart: on-failure
    ports:
      - "3030:3030"

  
