ingress:
  name: ingress-service-resource-helm
  replicaCount: 1
  class: nginx
  rules:
    - http:
      paths: 
        - path: /
          type: Prefix
          backend:
            service:
              name: frontend-cluster-ip-service-helm
              port:
                number: 3030
