apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: resource
spec:
  type: {{ .Values.postgres.service.type }}
  selector: 
    component: {{ .Values.postgres.label }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}