apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: resource
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: resource-sharing-app-backend
          image: joty46/resource_sharing_app-backend:v34
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: 
                name: backend-configmap
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credential
                  key: postgres_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credential
                  key: postgres_password