apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: resource
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: resource-sharing-app-frontend
          image: asia-south2-docker.pkg.dev/fit-brand-447203-e1/myapp/frontend:v1
          ports:
            - containerPort: 3030

      