apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: resource
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: resource-sharing-app-frontend
          image: joty46/resource_sharing_app-frontend:v1
          ports:
            - containerPort: 3000
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.97.167.209 
        searches:
          - backend-cluster-ip-service.resource.svc.cluster.local