apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.config.name }}
  labels:
    component: {{ .Values.api.label }}
data:
{{- range .Values.api.config.data }}
  {{ .key }}: {{ .value | quote }}
{{- end}}  