app:
  name: frontend-deployment-helm
  replicaCount: 1
  label: web
  container:
    name: resource-sharing-app-frontend
    image: asia-south2-docker.pkg.dev/fit-brand-447203-e1/myapp/frontend:v2
    port: 3030
  service:
    name: frontend-cluster-ip-service-helm
    type: ClusterIP
    port: 3030