FROM python:3.12-slim AS builder

WORKDIR /code

COPY Resource/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY Resource .

FROM builder AS run

WORKDIR /code

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

COPY --from=builder code/main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# CMD uvicorn main:app --host 0.0.0.0 --port ${PORT:- 8000}