apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  namespace: resource
spec:
  type: {{ .Values.api.service.type }}
  selector:
    component: {{ .Values.api.label }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}