apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  {{- range .Values.ingress.rules }}
    - http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .type }}
            backend:
              service:
                name: {{ .backend.service.name | quote }}
                port: 
                  number: {{ .backend.service.port.number }}
        {{- end }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.class }}
