apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.config.name }}
  namespace: resource
  labels:
    component: {{ .Values.postgres.label }}
data:
{{- range .Values.postgres.config.data }}
  {{ .key }}: {{ .value }}
{{- end}}  