kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app.service.name }}
  namespace: resource
spec:
  type: {{ .Values.app.service.type }}
  selector:
    component: web
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      nodePort: {{ .Values.app.service.nodePort }}