repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

helmBinary: "/usr/local/bin/helm" 
releases:
  - name: db-release
    chart: bitnami/postgresql
    namespace: resource
    values:
      - ./values.yaml

  - name: resource-frontend
    chart: ./app-helm
    namespace: resource
    values:
      - ./app-helm/values.yaml

  - name: resource-backend 
    chart: ./resource-helm-chart
    namespace: resource
    values:
      - ./resource-helm-chart/values.yaml
  - name: resource-ingress 
    chart: ./ingress
    namespace: resource
    values:
      - ./ingress/values.yaml
  - name: resource-ingress-helm 
    chart: ingress-nginx/ingress-nginx
    namespace: resource
    values:
      - ./ingressvalue.yaml
  
  