api:
  name: backend-deployment-helm
  replicaCount: 1
  label: app
  container:
    name: resource-sharing-app-backend
    image: asia-south2-docker.pkg.dev/fit-brand-447203-e1/myapp/backend:latest
    port: 8000
  service:
    name: backend-cluster-ip-service-helm
    type: ClusterIP
    port: 8000
  config:
    name: backend-configmap-helm
    data:
       - key: DB_USER
         value: postgres
       - key: DB_PASSWORD
         value: supersecretpassword
       - key: DB_NAME
         value: crud_db
       - key: DB_PORT
         value: 5432
       - key: DB_HOST
         value: db-release-postgresql.resource.svc.cluster.local
